### ISSUE TITLE
Loading rust-mode fails with "Symbol's function definition is void: make-cm-mode"

### ISSUE THREAD

**Issue by ngoldbaum** [rust-lang/rust-mode#114]
I'm unable to load rust mode in a GUI emacs session. It works in a terminal emacs session though.

The error is triggered by trying to switch to rust-mode in an open buffer (`M-x rust-mode`). I'm using emacs 24.5.1 on OSX.

**Comment by MicahChalmer** [comment]
Were you trying to install rust-mode from Marmalade?  That package is very old and outdated and should be removed.  (See #44.  Marmalade is no longer mentioned in the README, but the outdated package still exists there and should be removed.)  I ask because I searched for "emacs make-cm-mode" and it got to this old reddit thread: https://www.reddit.com/r/rust/comments/2s10ah/anyone_else_use_emacs_rustmode_its_not_working/

It looks like very old versions of rust-mode contained a function called `make-cm-mode` but it has not been in the code for a very long time.

**Comment by ngoldbaum** [comment]
That's it, thank you. It's definitely still happening with the version installed via the emacs package manager.

**Comment by ngoldbaum** [comment]
For some reason I had `rust-mode-0.1.0` in my `load-path`. I guess that came from Marmelade? In any case, after running `package-list-packages` I was able to download the latest version. After deleting the out of date rust-mode package in my .emacs.d, I'm now able to use rust-mode in my GUI emacs session.

Thanks for the tip!
