### ISSUE TITLE
Integrate support for rustfmt

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#120]
I think it would be great to have support for rustfmt integrated into the default rust-mode package. I think it should be bound to some hot-key and (not by default) configurable to run on every save. However, it looks like @fbergroth has already done [all the hard work](https://github.com/fbergroth/emacs-rustfmt/). Perhaps we can merge these two projects?

I wasn't sure where to open this issue, but I decided to do it here so that people could weigh in on whether they would like this support at all. But please @fbergroth I'd like to know your take as well -- would you prefer to keep emacs-rustfmt distinct?

**Comment by steveklabnik** [comment]
In rust.vim we have both a function that you can bind to a keypress, as well as a config to run it on save.

**Comment by blaenk** [comment]
Yeah that's pretty standard it seems. clang-format and emacs-rustfmt provide those two options as well.

With respect to merging the two projects, I know it's not up to me, but I think I'm for it. I can't really envision a scenario in which someone would want emacs-rustfmt but not rust-mode. It also makes for a more out-of-the-box rust experience on emacs, instead of having to install a separate package. Especially because rustfmt is/will be the community standard/sanctioned formatting tool, I would expect to see support for it in the definitive rust package.

It seems to me like `C-c C-f` is the "standard" binding for this, as shown in the emacs-rustfmt repo. I also use it for clang-format. I make sure to bind it in `rust-mode-map` to avoid it clobbering other binds:

``` elisp
(use-package rustfmt
  :defer t
  :init
  (defun blaenk/rustfmt ()
    (bind-key "C-c C-f" 'rustfmt-format-buffer rust-mode-map))

  (add-hook 'rust-mode-hook 'blaenk/rustfmt))
```

**Comment by fbergroth** [comment]
Sure, I wouldn't mind merging emacs-rustfmt with rust-mode. Would you prefer me making a PR?

**Comment by nikomatsakis** [comment]
@fbergroth a PR would be great!

**Comment by fbergroth** [comment]
@nikomatsakis see #121 :)
