### ISSUE TITLE
ripgrep integration

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#176]
ripgrep is awesome! We should have some nice integration into rust-mode by default! =)

**Comment by mattiasb** [comment]
In general that kind of stuff is outside the scope of a major mode in Emacs and more in the territory of minor-modes since it works with any language.

In the case of ripgrep there are already a couple of minor-modes  available including integration with projectile which is for general project management.

**Comment by tromey** [comment]
I agree; I'm going to close this.  We can reopen if there's some specific way that rust-mode and ripgrep could integrate better, beyond the generic grep-mode type thing.
