### ISSUE TITLE
support for Rust Language Server

### ISSUE THREAD

**Issue by bbigras** [rust-lang/rust-mode#181]
Any plans to use [Rust Language Server](https://internals.rust-lang.org/t/introducing-rust-language-server-source-release/4209)?

**Comment by nikomatsakis** [comment]
I've been thinking about toying with that, but if I'm honest it's probably way above my skill in elisp. =)

**Comment by brunoqc** [comment]
I would be interested too but my skill in elisp are limited to being able to edit my emacs config files. :) Now that emacs supports "shared/dynamic libraries" I wonder if it could be written in Rust.

Some people began to work on LSP support but I don't know if they will continue. https://github.com/sourcegraph/emacs-lsp

2 people were also interested to work on this on the internal rust forum. I just asked them if they did any progress.
https://internals.rust-lang.org/t/introducing-rust-language-server-source-release/4209/31?u=bbigras

**Comment by mgeisler** [comment]
There is now an [emacs-lsp](https://github.com/vibhavp/emacs-lsp) package on Melpa which seems to be updated regularly.

**Comment by bbigras** [comment]
> There is now an emacs-lsp package on Melpa which seems to be updated regularly.

Yeah I'm going to try this one when RLS will be installable with rustup (see https://users.rust-lang.org/t/announcing-rustup-1-1-0/10242).

**Comment by tromey** [comment]
Given that emacs-lsp exists, I'm inclined to think that this bug can be closed -- or is there some change to be made in rust-mode?

**Comment by bbigras** [comment]
Does rust-mode do things like run cargo to check for compilation errors that could conflict or be redundant when using emacs-lsp?

**Comment by nikomatsakis** [comment]
@tromey I don't know how realistic it is, but I would like it if there were some "easy way" to install rust-mode in emacs that covered rustfmt, RLS setup, and other configuration. Maybe that's a separate bug.

**Comment by sbidin** [comment]
RLS is [now installable via rustup](http://www.jonathanturner.org/2017/04/rls-now-in-nightly.md.html).

**Comment by Dushistov** [comment]
@nikomatsakis 

> but I would like it if there were some "easy way" to install rust-mode in emacs that covered rustfmt, RLS setup, and other configuration

At now I use:

- [flycheck-rust](https://github.com/flycheck/flycheck-rust) for online syntax checking
- [cargo](https://github.com/kwrooijen/cargo.el) for compiling, syntax checking and
  and also it has great feature `cargo-process-current-test` if your cursor inside `#[test]`
  you run this elisp function and emacs run only this rust test function.
- [emacs-racer](https://github.com/racer-rust/emacs-racer) for obvious reasons
- [rust-playground](https://github.com/grafov/rust-playground) for fast way to check some 
  syntax construction (running snippet with ctrl+enter is great)
- and `rust-mode` of course

I not use `rls` via [emacs-lsp](https://github.com/vibhavp/emacs-lsp), because of completetions work too slow in compare with [emacs-racer](https://github.com/racer-rust/emacs-racer).

Bad things that these are separate tools, and some times it conflict with each other,
for example if you change code  and run `cargo build` with active `flycheck-mode`, then
one of two operations: syntax check or `cargo build` hangs with message like this `Blocking waiting for file lock on build directory`.

It would be great to combine this tools on basis of some emacs ide framework, like 
http://cedet.sourceforge.net/ede.shtml (which is part of emacs 25 as I know).

**Comment by sondr3** [comment]
I think that preferably most of those packages should be combined into one package for Rust, but it would require several people merging their projects with what becomes the defacto package. I think @nikomatsakis mentioned this somewhere else but he wanted `rust-mode` to be everything that is required to use Rust in Emacs. I fully agree with this but you have five or six packages at least that would need to merge with it.

**Comment by Dushistov** [comment]
What about integration of [lsp-rust](https://github.com/emacs-lsp/lsp-rust) as starting point?

It is very small package with `< 50` lines of code. That take care about launch `rls` and find `Cargo.toml`.  If rust-mode can take care about this stuff this should simplify things.

**Comment by tromey** [comment]
> What about integration of lsp-rust as starting point?

That has `lsp-mode` as a dependency, which is quite a bit larger.  At some point I think it would make sense to just make these dependencies of rust-mode.  Maybe when RLS lands in a stable release?  Also the caveats in the lsp-rust README are worrying.

**Comment by sondr3** [comment]
The warning I think comes because it doesn't run asynchronously, so when it hangs, Emacs hangs. I'm fairly certain there are ways to work around this for Emacs, but not sure how easy or good the solutions are.

**Comment by briprowe** [comment]
It's probable that [CIDER](https://github.com/clojure-emacs/cider) has figured this out. Maybe we could take inspiration from it.

**Comment by jonathandturner** [comment]
I got RLS working in emacs.  There might be a simpler way, but here's what I did:

* Install [rust-mode](https://github.com/rust-lang/rust-mode)
* Install [flycheck](http://www.flycheck.org/en/latest/)
* Install [markdown-mode](https://jblevins.org/projects/markdown-mode/)
* Install [lsp-mode](https://github.com/emacs-lsp/lsp-mode#installation)
* Install [lsp-rust](https://github.com/emacs-lsp/lsp-rust#setup)

**Comment by nikomatsakis** [comment]
I tried it and also got it working. A bit finnicky to do. No idea how we could streamline that.

**Comment by tromey** [comment]
Now GNU's ELPA has `eglot`, which is another LSP client.

**Comment by nikomatsakis** [comment]
eglot works great for me; very "plug and play". https://github.com/joaotavora/eglot

**Comment by brotzeit** [comment]
I will update the readme and add some notes about lsp support in emacs.
