### ISSUE TITLE
Unable to set buffer local before-save-hook

### ISSUE THREAD

**Issue by CSRaghunandan** [rust-lang/rust-mode#183]
I tried to set a buffer local before save hook like below:
```
(add-hook 'before-save-hook
          (lambda ()
            (xah-clean-whitespace)
            (rust-format-buffer)
            (force-backup-of-buffer)) t t)
```

But, looks like `before-save-hook` is being to `rust--before-save-hook` and it's not applying the anonymous function I've written above. With my little knowledge of elisp, i'm unable to figure out what's going on :(

**Comment by tromey** [comment]
Where is this invocation to `add-hook`?

I tried it interactively by doing an `add-hook` from `rust-mode-hook`, like:

```
(defun tromey-test-ws ()
  (delete-trailing-whitespace (point-min) (point-max)))
(defun tromey-attach-rust-mode-hacks ()
  (add-hook 'before-save-hook #'tromey-test-ws t t))
(add-hook 'rust-mode-hook #'tromey-attach-rust-mode-hacks)
```

This worked fine.

If that line just appears as-is in your `.emacs`, then the problem is the final argument to `add-hook` -- passing `t` here means that the addition only affects the current buffer.

**Comment by CSRaghunandan** [comment]
This issue seems to be fixed. We can close the issue.

I'm setting the `before-save-hook` for `rust-mode` in [here](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-rust.el#L42) in my emacs config and that seems to work fine.
