### ISSUE TITLE
Can't use rustfmt nightly

### ISSUE THREAD

**Issue by philn** [rust-lang/rust-mode#223]
I have tried to set this:
`(setq rust-rustfmt-bin "rustup run nightly rustfmt")`

And also with absolute path to rustup, but it doesn't work:

`Error: (error "Could not locate executable \"/Users/philn/.cargo/bin/rustup run nightly rustfmt\"")`

**Comment by philn** [comment]
As a workaround I can write a wrapper shell script I suppose, but ... meh :)

**Comment by kyren** [comment]
This is also important if you are trying to work around the rustfmt bug that caused #215 on macos, because it is difficult (impossible?) to set DYLD_LIBRARY_PATH in a way that makes it to the invocation of rustfmt when using gui emacs, because of SIP on macos.  If `rust-rustfmt-bin` was instead something like `rust-rustfmt-command` that would be amazing.

**Comment by xianghx** [comment]
so stupid:
  (setq rust-format-on-save t)
  (setq rust-rustfmt-bin "~/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/rustfmt")

**Comment by philn** [comment]
Quoting the issue description: `And also with absolute path to rustup, but it doesn't work`

**Comment by kyren** [comment]
Using the absolute path should now work without futzing with LD_LIBRARY_PATH etc IF you install `rustfmt-preview` via rustup.

**Comment by philn** [comment]
Ok, I should give it a try again, thanks for the update :)

**Comment by philn** [comment]
Yes it works as expected now, yay!
