### ISSUE TITLE
emacs23 support in travis is failing

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#27]
Currently emacs23 tests are broken. @pnkfelix and I were unable to reproduce the failures locally. For now we disabled emacs23 testing, but we'd like to re-enable it. We'll need some advice on what is wrong or how to reproduce the problems locally.

Example failures:

https://travis-ci.org/rust-lang/rust-mode/jobs/49740311

cc @MicahChalmer

**Comment by pnkfelix** [comment]
(to be clear: we were unable to run the test suite on emacs23 locally.  Its not like we ran the test suite and the tests appeared to succeed.)

**Comment by MicahChalmer** [comment]
Since the #25 was closed and this is still open, I'll repeat myself here as to how to run ERT locally with emacs 23:

ERT was a standalone package through emacs 23, but was then made part of emacs for emacs 24.  In the travis config, I have it download it from https://raw.githubusercontent.com/ohler/ert/c619b56c5bc6a866e33787489545b87d79973205/lisp/emacs-lisp/ert.el (that URL is still present in the .travis.yml here, but the use of it in the build has been disabled by #26.  Grab it and put it in a place where emacs will know where to find it (the site-lisp directory where it's installed, for instance) and the tests will run.

I might submit a PR adding some info to the README on emacs version support, including instructions on how to run the tests locally.  #21 helps.
