### ISSUE TITLE
Unable to view package info in `package-list-packages`

### ISSUE THREAD

**Issue by condy0919** [rust-lang/rust-mode#531]
It echos

``` text
package--print-email-button: Wrong type argument: listp, "Mozilla"
```

in echo area on typing <kbd>RET</kbd> on rust-mode.

**Comment by psibi** [comment]
Unfortunately I'm not able to reproduce this, could be because I'm using Emacs 29.1. I believe you are using Emacs 30/snapshot version ? 

I do see that there is no email field in `rust-mode.el` based on the docs here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html

Could you see if adding an email would fix it for you ?

**Comment by condy0919** [comment]
> Could you see if adding an email would fix it for you ?

yep

**Comment by psibi** [comment]
Cool, can you send a PR ? But probably use this mail instead:

```
rust-mode@noreply.github.com
```

I'm open to other suggestions too.
